#!/bin/bash

set -x

if ! (( ssh-add -L | grep mac_id_rsa )) ; then
  ssh-add ~/.ssh/mac_id_rsa
fi

tagNumber=`git branch | grep -e "^*" | cut -d' ' -f 2`
echo "$tagNumber"

npm run test-travis &&

git checkout master &&
git merge "$tagNumber" &&
npm run clean &&
npm run build &&
git add . &&
git commit -m 'auto-build on `date +%Y%m%d`' ;
git push origin master &&
git checkout "$tagNumber" &&

echo "wasya_react build ok"
